server:
  port: 8082

spring:
  application:
    name: content-service
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: postgres
    password: QWer2345
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

# Feign 配置
spring.cloud.openfeign.circuitbreaker.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.example: INFO
